theme: jekyll-theme-slate
title: Reading List
description: Books I've been reading lately. Not a complete list and certainly not an endorsement of their contents. Reach out with your recommended reads or to discuss anything here, I most likely have some summary notes I am happy to share.
